version: "3.7"

volumes:
  database_vol1:

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn ${NODE_ENV}
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:3333
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: bitnami/postgresql:latest
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database_vol1:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$TYPEORM_USERNAME"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
